### ISSUE TITLE
Functionality to edit node in Linked List?

### ISSUE THREAD

**Issue by wjrivera** [kilianc/node-linkedlist#3]
Does this support edit functionality? Like Java function .set(#, data)?
Thank you

**Comment by kilianc** [comment]
I think we could easily add it, both `#get` and `#set`

**Comment by wjrivera** [comment]
Man, that would be awesome!

**Comment by kilianc** [comment]
does out of bounds throw ?

**Comment by kilianc** [comment]
can you give it a try before I publish to npm ? just `npm iinstall kilianc/node-linkedlist`

**Comment by wjrivera** [comment]
Sorry it took a while to get back to you.  I tried set and get and they work flawless.  Thank you so much!
